version: '3.8'

services:

  test:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: python -m pytest
    depends_on:
      - redis
      - worker
    volumes:
      - ./data:/usr/src/app/data
    links:
      - redis
  web:
    build: .
    ports:
      - 8004:8000
    command: uvicorn api.__main__:api --host 0.0.0.0 --reload
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    links:
      - redis

  worker:
    restart: always
    build: .
    command: celery --app api.utils.tasks.celery_client worker --loglevel=info --logfile=data/logs/celery.log
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    links:
      - redis

  redis:
    restart: always
    image: redis:6-alpine
    volumes:
      - "./data/redis:/data"
    ports:
      - "6379:6379"

  dashboard:
    build: .
    command:  celery --app=api.utils.tasks.celery_client flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker